### ISSUE TITLE
URL do feed RSS

### ISSUE THREAD

**Issue by ferhrosa** [gamedevbr-podcast/gamedevbr-podcast.github.io#1]
A URL do link RSS do menu do site é de um feed que não está em formato válido do iTunes.
Seria bom ter também o link para o feed do iTunes, para que possamos adicionar seu podcast em outros aplicativos, que usam o feed como base.

A URL do site a que me refiro é essa: https://gamedevbr-podcast.github.io/rss
A URL do feed do iTunes é essa: https://gamedevbr-podcast.github.io/podcast/feed/

**Comment by cicanci** [comment]
Obrigado pelo feedback! Adicionei as duas URLs no menu, Feed e iTunes.
Abraço!
